Repository fast-excel/fastexcel, pull requests merged in 2025-03, with the labels that each got.

#260 doc: add JavaDoc and inline comments for simple test
  fastexcel-core/src/main/java/cn/idev/excel/read/processor/DefaultAnalysisEventProcessor.java
  fastexcel-test/src/test/java/cn/idev/excel/test/core/simple/SimpleData.java
  fastexcel-test/src/test/java/cn/idev/excel/test/core/simple/SimpleDataListener.java
  fastexcel-test/src/test/java/cn/idev/excel/test/core/simple/SimpleDataTest.java
Labels: documentation

#283 fix: failure unit test
  fastexcel-test/src/test/java/cn/idev/excel/test/temp/WriteV33Test.java
  fastexcel-test/src/test/java/cn/idev/excel/test/temp/fill/FillTempTest.java
  fastexcel-test/src/test/java/cn/idev/excel/test/temp/poi/Poi2Test.java
  fastexcel-test/src/test/java/cn/idev/excel/test/temp/poi/PoiDateFormatTest.java
  fastexcel-test/src/test/java/cn/idev/excel/test/temp/poi/PoiFormatTest.java
  fastexcel-test/src/test/java/cn/idev/excel/test/temp/read/HeadReadTest.java
  fastexcel-test/src/test/java/cn/idev/excel/test/temp/write/TempWriteTest.java
  fastexcel-test/src/test/resources/cache/headt1.xls
  fastexcel-test/src/test/resources/cache/t2.xlsx
  fastexcel-test/src/test/resources/poi/last_row_number_test.xlsx
  fastexcel-test/src/test/resources/poi/last_row_number_xssf_test.xlsx
Labels: documentation

#284 fix: maven properties and module exception for reflection
  fastexcel-support/pom.xml
  pom.xml
Labels: good first issue

#287 fix: update head size calculation
  fastexcel-core/src/main/java/cn/idev/excel/read/listener/ModelBuildEventListener.java
  fastexcel-test/src/test/java/cn/idev/excel/test/core/head/MaxHeadReadListener.java
  fastexcel-test/src/test/java/cn/idev/excel/test/core/head/MaxHeadSizeData.java
  fastexcel-test/src/test/java/cn/idev/excel/test/core/head/MaxHeadSizeTest.java
  fastexcel-test/src/test/resources/temp/issue220/test01.xlsx
  fastexcel-test/src/test/resources/temp/issue220/test02.xlsx
  fastexcel-test/src/test/resources/temp/issue220/test03.xlsx
Labels: bug, development completed

#289 style: update code style configuration for multiple languages
  style/codestyle/idea/fastexcel_codestyle.xml
Labels: documentation
